### ISSUE TITLE
Plugins Roadmap

### ISSUE THREAD

**Issue by tim-sueberkrueb** [liri-project/liri-browser#162]
Plugins Roadmap for v0.4 (*Liri API 0.1*):
* [x] Initial plugin support
* [x] Handle omniplet functioniality
* [ ] Refactor all omniplets as plugins
  * leave history and bookmark in core?
  * @pierremtb?
* [ ] Check security policies and deny

Plugins Roadmap for v0.5 (*Liri API 0.2*):
* [ ] handle different api versions

More functionality to come soon ...

This issue will be assigned to v0.5 as soon as all v0.4 functionality is ready in master.
Current plugin development takes place on branch [plugin-support](https://github.com/liri-project/liri-browser/tree/plugin-support).

**Comment by pierremtb** [comment]
@tim-sueberkrueb Regarding omniplets that need to have access to bookmarks or history, we might keep them as core, so we don't have to give plugins access to users bookmarks or history, you know what I mean ?

**Comment by tim-sueberkrueb** [comment]
@pierremtb either that or we'd introduce a special permission for that which is reserved for core plugins.

**Comment by tim-sueberkrueb** [comment]
@pierremtb I now integrated all omniplets as plugins. There's also now permission support. Plugins can only make an API call or register an `on` callback if they list the feature in their `manifest.json` and the permission was granted in `config/liri-config.json`. Later there will be an user interface for this (smth like a "Plugin Store" tab where the user can define for each plugin). Some functions are `common` which means they can be accessed without any special permission. Eg. `liri.print`. Are you okay with this? Should I remove the current omniplet handling?

**Comment by tim-sueberkrueb** [comment]
Initial wiki page: https://github.com/liri-project/liri-browser/wiki/Plugin-API

**Comment by pierremtb** [comment]
@tim-sueberkrueb Wow this is so nice ! Awesome work
Yeah do what you want

**Comment by tim-sueberkrueb** [comment]
@pierremtb thx :)

**Comment by tim-sueberkrueb** [comment]
v0.4 Plugin Support (Plugin API v0.1) is ready and in `master`. Wiki pages: https://github.com/liri-project/liri-browser/wiki#developer-guides
